EduHome2/EduHome2/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHome2.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHome2/EduHome2/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHome2.Controllers
{
    public class BlogsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHome2/EduHome2/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHome2.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHome2/EduHome2/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHome2.Controllers
{
    public class EventsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHome2/EduHome2/Views/Shared/Components/Header/Default.cshtml
@model Bio
<header class="top">
            <div class="header-top">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-8 col-xs-12">
                            <div class="header-top-left">
                                <p>HAVE ANY QUESTION ?  +@Model.PhoneNumber</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="header-top-right text-right">
                                <ul>
                                    <li><a href="login.html">login</a></li>
                                    <li><a href="signup.html">signup</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-area two header-sticky">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-6">
                            <div class="logo">
                                <a href="index.html"><img src="~/img/logo/@Model.HeaderLogo" alt="eduhome" /></a>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-6">
                            <div class="content-wrapper text-right">
                                <!-- Main Menu Start -->
                                <div class="main-menu">
                                    <nav>
                                        <ul>
                                            <li><a asp-controller="Home" asp-action="Index">Home</a>

                                            </li>
                                            <li><a asp-controller="About" asp-action="Index">About</a>

                                            </li>

                                            <li><a asp-controller="Courses" asp-action="Index">courses</a>

                                            </li>
                                            <li><a asp-controller="Events" asp-action="Index">event</a>

                                            </li>
                                            <li class="hidden-sm"><a asp-controller="Teachers" asp-action="Index">teacher</a>

                                            </li>
                                            <li><a asp-controller="Blogs" asp-action="Index">blog</a>

                                            </li>
                                            <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>

                                        </ul>
                                    </nav>
                                </div>
                                <!--Search Form Start-->
                                <div class="search-btn">
                                    <ul data-toggle="dropdown" class="header-search search-toggle">
                                        <li class="search-menu">
                                            <i class="fa fa-search"></i>
                                        </li>
                                    </ul>
                                    <div class="search">
                                        <div class="search-form">
                                            <form id="search-form" action="#">
                                                <input type="search" placeholder="Search here..." name="search" />
                                                <button type="submit">
                                                    <span><i class="fa fa-search"></i></span>
                                                </button>
                                            </form>                                
                                        </div>
                                    </div>
                                </div>	
                                <!--End of Search Form-->
                                <!-- Main Menu End -->
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="mobile-menu hidden-lg hidden-md hidden-sm"></div> 
                        </div>
                    </div>
                </div>
            </div>
        </header>