EduHome2/EduHome2/ViewComponents/FooterViewComponent.cs
using EduHome2.DAL;
using EduHome2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome2.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly AppDbContext _db;
        public FooterViewComponent(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio bio = await _db.Bios.FirstAsync();
            return View(bio);
        }
    }
}

EduHome2/EduHome2/ViewComponents/HeaderViewComponent.cs
using EduHome2.DAL;
using EduHome2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome2.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _db;
        public HeaderViewComponent(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio bio = await _db.Bios.FirstAsync();
            return View(bio);
        }
    }
}

EduHome2/EduHome2/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:37:50 GMT -->
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Eduhome - Educational HTML Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="~/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/animate.css">
        <link rel="stylesheet" href="~/css/meanmenu.css">
        <link rel="stylesheet" href="~/css/magnific-popup.css">
        <link rel="stylesheet" href="~/css/owl.carousel.min.css">
        <link rel="stylesheet" href="~/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/et-line-icon.css">
        <link rel="stylesheet" href="~/css/reset.css">
        <link rel="stylesheet" href="~/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/material-design-iconic-font.min.css">
        <link rel="stylesheet" href="~/css/style.css">
        <link rel="stylesheet" href="~/css/responsive.css">
        <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
         
        <!-- Header Area Start -->
        @await Component.InvokeAsync("Header")
        <!-- Header Area End -->

@RenderBody()

                                 <!-- Footer Start -->
        @await Component.InvokeAsync("Footer")
        <!-- Footer End -->

        <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/jquery.meanmenu.js"></script>
        <script src="~/js/jquery.magnific-popup.js"></script>
        <script src="~/js/ajax-mail.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/jquery.mb.YTPlayer.js"></script>
        <script src="~/js/jquery.nicescroll.min.js"></script>
        <script src="~/js/plugins.js"></script>
        @RenderSection("Scripts" , false)
        <script src="~/js/main.js"></script>
    </body>

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:41:25 GMT -->
</html>

EduHome2/EduHome2/Views/Shared/_LoadMoreCoursesPartial.cshtml
@model List<Course>

@foreach(Course course in Model){

         <div class="col-md-4 col-sm-6 col-xs-12">
                                <div class="single-course mb-70">
                                    <div class="course-img">
                                        <a href="course-details.html"><img src="~/img/course/@course.Image" alt="course">
                                            <div class="course-hover">
                                                <i class="fa fa-link"></i>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="course-content">
                                        <h3><a href="course-details.html">@course.Name</a></h3>
                                        <p>@course.Description</p>
                                        <a class="default-btn" href="course-details.html">read more</a>
                                    </div>   
                                </div>
                            </div>
}